site_name: 王国庆的博客
site_description: 王国庆的技术知识库
site_url: https://codingriver.github.io/
repo_url: https://github.com/codingriver/codingriver.github.io
edit_uri: edit/master/docs/
use_directory_urls: false
theme:
  name: material
  language: zh
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换暗色模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换亮色模式
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    - header.autohide
nav:
- 首页: index.md
- 关于: about.md
- 全部栏目: all-articles.md
- 全部分类: all-categories.md
- MkDocs 博客方案: MkDocs博客方案.md
- 标签: tags/index.md
- 项目记录与随笔:
  - 栏目首页: ANote/index.md
  - 00-Test: ANote/00-Test.md
  - '2018-09-26': ANote/2018-09-26.md
  - CSharp笔记: ANote/CSharp笔记.md
  - CSharp记录: ANote/CSharp记录.md
  - DOTS笔记: ANote/DOTS笔记.md
  - DrawCall优化实战演讲稿: ANote/DrawCall优化实战演讲稿.md
  - EOC项目分析笔记1: ANote/EOC项目分析笔记1.md
  - EOC项目笔记: ANote/EOC项目笔记.md
  - Git笔记: ANote/Git笔记.md
  - IGG开发笔记: ANote/IGG开发笔记.md
  - IGG性能分析笔记: ANote/IGG性能分析笔记.md
  - Linux笔记: ANote/Linux笔记.md
  - NAS笔记: ANote/NAS笔记.md
  - PBR笔记: ANote/PBR笔记.md
  - ParticleEffectForUGUI使用教程: ANote/ParticleEffectForUGUI使用教程.md
  - SRPBatcher和GPUInstance: ANote/SRPBatcher和GPUInstance.md
  - SSH笔记: ANote/SSH笔记.md
  - Shader案例: ANote/Shader案例.md
  - Shader笔记: ANote/Shader笔记.md
  - Shader笔记2: ANote/Shader笔记2.md
  - Shell笔记: ANote/Shell笔记.md
  - UI笔记: ANote/UI笔记.md
  - Unity-URP笔记: ANote/Unity-URP笔记.md
  - Unity记录: ANote/Unity记录.md
  - caddy笔记: ANote/caddy笔记.md
  - cloudflare反向代理工具: ANote/cloudflare反向代理工具.md
  - golang笔记: ANote/golang笔记.md
  - jenkins记录: ANote/jenkins记录.md
  - shader记录: ANote/shader记录.md
  - socket测试结果: ANote/socket测试结果.md
  - unity编辑器笔记: ANote/unity编辑器笔记.md
  - web开发笔记: ANote/web开发笔记.md
  - 其他记录: ANote/其他记录.md
  - 包体大小优化笔记: ANote/包体大小优化笔记.md
  - 操作系统笔记: ANote/操作系统笔记.md
  - 日常使用命令: ANote/日常使用命令.md
  - 日常笔记: ANote/日常笔记.md
  - 梳理: ANote/梳理.md
  - 矩阵笔记: ANote/矩阵笔记.md
  - 视频处理: ANote/视频处理.md
  - 记录: ANote/记录.md
  - 设计模式笔记: ANote/设计模式笔记.md
  - 问题: ANote/问题.md
- Android 开发:
  - 栏目首页: Android/index.md
  - Android-App内打开自带浏览器: Android/Android-App内打开自带浏览器.md
  - Android　分享App-Icon透明图片到微信变黑的问题: Android/Android　分享App-Icon透明图片到微信变黑的问题.md
  - Android，iOS-通过浏览器打开app: Android/Android，iOS-通过浏览器打开app.md
- 图形学:
  - 栏目首页: Graphics/index.md
  - DirectX环境搭建: Graphics/DirectX环境搭建.md
- iOS 开发:
  - 栏目首页: IOS/index.md
  - CSharp基础笔记: IOS/CSharp基础笔记.md
  - IOS中Xcode-framework无法识别headers目录问题，头文件读不出来: IOS/IOS中Xcode-framework无法识别headers目录问题，头文件读不出来.md
  - Xcode工程配置: IOS/Xcode工程配置.md
  - Xcode查看真机app沙盒内容，查看app缓存（Cache）文件: IOS/Xcode查看真机app沙盒内容，查看app缓存（Cache）文件.md
  - Xcode项目发布App-Store商品审核: IOS/Xcode项目发布App-Store商品审核.md
  - iOS-11-升级后无法真机调试（could-not-locate-device-support-files）: IOS/iOS-11-升级后无法真机调试（could-not-locate-device-support-files）.md
  - ios-object-c-UIImage图片缩放: IOS/ios-object-c-UIImage图片缩放.md
  - ios-object-c-获取App图标使用的图片名字AppIcon: IOS/ios-object-c-获取App图标使用的图片名字AppIcon.md
  - ios-配置ItunesConnect添加应用: IOS/ios-配置ItunesConnect添加应用.md
  - ios配置开发者证书及添加AppID: IOS/ios配置开发者证书及添加AppID.md
  - xcode接sdk时报错Undefined-symbols-for-architecture-arm64-: IOS/xcode接sdk时报错Undefined-symbols-for-architecture-arm64-.md
- 系统基础:
  - 栏目首页: basesystem/index.md
  - ASCII，Unicode和UTF-8: basesystem/ASCII，Unicode和UTF-8.md
  - URL编码与解码原理: basesystem/URL编码与解码原理.md
  - 为什么用补码，为什么有符号单字节最小是-128: basesystem/为什么用补码，为什么有符号单字节最小是-128.md
  - 位操作符介绍: basesystem/位操作符介绍.md
  - 位运算实现加减乘除: basesystem/位运算实现加减乘除.md
  - 十进制和二进制互相转换: basesystem/十进制和二进制互相转换.md
  - 原码、反码、补码和移码详解: basesystem/原码、反码、补码和移码详解.md
  - 多字节大小端说明: basesystem/多字节大小端说明.md
  - 深入理解计算机系统第二章部分练习题: basesystem/深入理解计算机系统第二章部分练习题.md
- C# 语言与工程:
  - 栏目首页: csharp/index.md
  - C#-Unicode编码和中文互转: csharp/CSharp-Unicode编码和中文互转.md
  - CSharp中Struct内存大小: csharp/CSharp中Struct内存大小.md
  - CSharp用Process类调用cmd执行及命令行首字母乱码问题: csharp/CSharp用Process类调用cmd执行及命令行首字母乱码问题.md
  - C# 特性详解（Attribute）: csharp/CSharp的特性详解.md
  - CSharp语言6-字符串插值: csharp/CSharp语言6-字符串插值.md
  - Enum_Int_String的互相转换: csharp/Enum_Int_String的互相转换.md
  - IL指令集: csharp/IL指令集.md
  - SynchronizationContext线程上下文简单说明: csharp/SynchronizationContext线程上下文简单说明.md
  - C# async与await的使用说明: csharp/async与await的使用说明.md
  - new关键字的几种用法: csharp/new关键字的几种用法.md
  - 中文和unicode互转: csharp/中文和unicode互转.md
  - 俩问号和值类型加问号分别是什么意思: csharp/俩问号和值类型加问号分别是什么意思.md
  - 字符串比较效率测试: csharp/字符串比较效率测试.md
  - 客户端开发CSharp命名规范手册: csharp/客户端开发CSharp命名规范手册.md
  - 闭包Closure: csharp/闭包Closure.md
- 数据结构与算法:
  - 栏目首页: datastruct/index.md
  - AVL树详解: datastruct/AVL树详解.md
  - A星算法理解: datastruct/A星算法理解.md
  - 二叉查找树: datastruct/二叉查找树.md
  - 伸展树详解: datastruct/伸展树详解.md
  - 十大经典排序算法及比较与分析: datastruct/十大经典排序算法及比较与分析.md
  - 树和二叉树基本讲解: datastruct/树和二叉树基本讲解.md
- 数据结构基础:
  - 栏目首页: datastructbase/index.md
  - 浮点数的内存存储和运算: datastructbase/浮点数的内存存储和运算.md
- Lua 语言:
  - 栏目首页: lua/index.md
  - lua中类的实现: lua/lua中类的实现.md
  - lua闭包和and-or操作符及其它的说明: lua/lua闭包和and-or操作符及其它的说明.md
- 数学与图形学基础:
  - 栏目首页: math/index.md
  - LinearEyeDepth推导: math/LinearEyeDepth推导.md
  - 三角函数和差公式的推导: math/三角函数和差公式的推导.md
  - 两个平面矩形相交（不旋转）: math/两个平面矩形相交（不旋转）.md
  - 基本求导法则与导数公式: math/基本求导法则与导数公式.md
  - 屏幕空间变换: math/屏幕空间变换.md
  - 微分和积分数学公式大全: math/微分和积分数学公式大全.md
  - 法线变换矩阵推导: math/法线变换矩阵推导.md
  - 点乘和叉乘的计算和应用: math/点乘和叉乘的计算和应用.md
  - 线性代数的本质: math/线性代数的本质.md
  - 透视投影变换推导: math/透视投影变换推导.md
  - 透视校正差值: math/透视校正差值.md
  - 齐次坐标的意义: math/齐次坐标的意义.md
- 工具与系统:
  - 栏目首页: other/index.md
  - 3500个常用汉字(字体裁剪用): other/3500个常用汉字(字体裁剪用).md
  - GitHub-ssh失败Permission-denied-(publickey): other/GitHub-ssh失败Permission-denied-(publickey).md
  - Json的float单精度浮点数类型支持: other/Json的float单精度浮点数类型支持.md
  - LuaForWindows-安装报错: other/LuaForWindows-安装报错.md
  - MAC-创建-IPv6-WIFI热点，不用以太网接口: other/MAC-创建-IPv6-WIFI热点，不用以太网接口.md
  - SVN-trunk(主线)-branch(分支)-创建和合并教程: other/SVN-trunk(主线)-branch(分支)-创建和合并教程.md
  - SVN无法提交--a和--so文件: other/SVN无法提交--a和--so文件.md
  - Sourcetree-Mac安装跳过注册登陆和选择服务器: other/Sourcetree-Mac安装跳过注册登陆和选择服务器.md
  - Sourcetree基本使用教程: other/Sourcetree基本使用教程.md
  - Sourcetree安装教程（windows）: other/Sourcetree安装教程（windows）.md
  - VS2013+LUA代码高亮配置教程: other/VS2013+LUA代码高亮配置教程.md
  - VS2013创建新脚本自动添加版权声明，文件名，作者，创建时间等: other/VS2013创建新脚本自动添加版权声明，文件名，作者，创建时间等.md
  - Windows创建点开头的文件或者点开头的文件夹: other/Windows创建点开头的文件或者点开头的文件夹.md
  - Xlua-线程问题: other/Xlua-线程问题.md
  - linux gcc版本如何升级到gcc4.8.2: other/linux gcc版本如何升级到gcc4.8.2.md
  - mac设置Library 显示: other/mac设置Library 显示.md
  - Nodejs初始化配置: other/nodejs初始化配置.md
  - tar(child)-lbzip2-Cannotexec解决方法: other/tar(child)-lbzip2-Cannotexec解决方法.md
  - win10-iis-http建站: other/win10-iis-http建站.md
  - win7安装Vs2015失败的解决方案(安装vs多个版本的问题): other/win7安装Vs2015失败的解决方案(安装vs多个版本的问题).md
  - 三次握手和四次挥手: other/三次握手和四次挥手.md
  - 六种常用设计模式: other/六种常用设计模式.md
  - 添加网络位置（共享目录）: other/添加网络位置（共享目录）.md
  - 用astash 画UML类图: other/用astash 画UML类图.md
  - 申请TexturePacker免费注册码(2018年11月份申请的): other/申请TexturePacker免费注册码(2018年11月份申请的).md
- Shader 与图形学:
  - 栏目首页: shader/index.md
  - 泛光（Bloom）实现: shader/Bloom实现.md
  - Gamma和Linear及sRGB说明: shader/Gamma和Linear及sRGB说明.md
  - ShaderLearn-(一)漫反射: shader/ShaderLearn-(一)漫反射.md
  - ShaderLearn-(三)RampTex: shader/ShaderLearn-(三)RampTex.md
  - ShaderLearn-(二)镜面反射: shader/ShaderLearn-(二)镜面反射.md
  - Shader光照模型-漫反射: shader/Shader光照模型-漫反射.md
  - Shader光照模型-高光反射: shader/Shader光照模型-高光反射.md
  - Shader学习-1.1基础概要: shader/Shader学习-1.1基础概要.md
  - 【Shader学习】前言: shader/Shader学习-前言.md
  - Shader水波纹效果: shader/Shader水波纹效果.md
  - Shader法线纹理: shader/Shader法线纹理.md
  - Shader法线贴图: shader/Shader法线贴图.md
  - Shader法线贴图（世界空间）: shader/Shader法线贴图（世界空间）.md
  - Shader消融特效: shader/Shader消融特效.md
  - Shader纹理动画: shader/Shader纹理动画.md
  - 【Shader】常用函数（UnityShader内置函数、CG 和 GLSL 内置函数等）和内置变量: shader/UnityShader常用函数.md
  - 模糊实现: shader/模糊实现.md
  - 边缘光和流光特效: shader/边缘光和流光特效.md
  - 边缘光特效: shader/边缘光特效.md
- tags:
  - 栏目首页: tags/index.md
- Unity 开发:
  - 栏目首页: u3d/index.md
  - CSharp命名规范手册: u3d/CSharp命名规范手册.md
  - DrawCall优化实战: u3d/DrawCall优化实战.md
  - RenderDoc-调试: u3d/RenderDoc-调试.md
  - UGUI-Image图片置灰: u3d/UGUI-Image图片置灰.md
  - UGUI-Text换行问题: u3d/UGUI-Text换行问题.md
  - UGUI中CustomFont（BMFont）字体使用与制作: u3d/UGUI中CustomFont（BMFont）字体使用与制作.md
  - UGUI事件介绍: u3d/UGUI事件介绍.md
  - UGUI事件系统: u3d/UGUI事件系统.md
  - UGUI优化-使用镜像图片: u3d/UGUI优化-使用镜像图片.md
  - UGUI使用富文本RichText: u3d/UGUI使用富文本RichText.md
  - UGUI运用美术字体: u3d/UGUI运用美术字体.md
  - Unity Editor和Player日志文件的存放: u3d/Unity Editor和Player日志文件的存放.md
  - Unity-GameObject-销毁（Destroy）后的几种状态: u3d/Unity-GameObject-销毁（Destroy）后的几种状态.md
  - Unity-Texture2D的SetPiexl严重耗时的优化方案: u3d/Unity-Texture2D的SetPiexl严重耗时的优化方案.md
  - Unity-使用Android-Splash: u3d/Unity-使用Android-Splash.md
  - Unity-性能优化相关知识(转): u3d/Unity-性能优化相关知识(转).md
  - Unity-日志文件的存放: u3d/Unity-日志文件的存放.md
  - UnityEditor-iOS-Xcode报错: u3d/UnityEditor-iOS-Xcode报错.md
  - UnityProfiler使用Android真机连接测试: u3d/UnityProfiler使用Android真机连接测试.md
  - Unity中获取依赖信息出现其他未引用字体问题: u3d/Unity中获取依赖信息出现其他未引用字体问题.md
  - Unity切入后台，切入前台，获取焦点，失去焦点等: u3d/Unity切入后台，切入前台，获取焦点，失去焦点等.md
  - Unity判断机型是否为iPhoneX等: u3d/Unity判断机型是否为iPhoneX等.md
  - Unity加载场景: u3d/Unity加载场景.md
  - Unity和IOS交互char-作为方法返回值到CSharp中bug: u3d/Unity和IOS交互char-作为方法返回值到CSharp中bug.md
  - Unity平台宏定义常用说明: u3d/Unity平台宏定义常用说明.md
  - Unity截屏: u3d/Unity截屏.md
  - Unity渲染顺序: u3d/Unity渲染顺序.md
  - Unity粒子特效缩放: u3d/Unity粒子特效缩放.md
  - Unity脚本执行顺序: u3d/Unity脚本执行顺序.md
  - c++_structunion数据对齐: u3d/c++_structunion数据对齐.md
  - unity--android获取电量和wifi信号强度: u3d/unity--android获取电量和wifi信号强度.md
  - unity-3DCamera根据宽度适配(3D相机适配): u3d/unity-3DCamera根据宽度适配(3D相机适配).md
  - unity-Font-Test测试: u3d/unity-Font-Test测试.md
  - unity-ios审核ipv6: u3d/unity-ios审核ipv6.md
  - unity-响应Android返回键: u3d/unity-响应Android返回键.md
  - unity-打包Android报错CommandInvokationFailure--Unable-to-convert-classes-i: u3d/unity-打包Android报错CommandInvokationFailure--Unable-to-convert-classes-i.md
  - unity-模型显示锯齿问题: u3d/unity-模型显示锯齿问题.md
  - unity-脚本设置AssetBundleName和Variant: u3d/unity-脚本设置AssetBundleName和Variant.md
  - unity3d中的LayerMask用法: u3d/unity3d中的LayerMask用法.md
  - unity优化-相同模型的多个实例设置各自的颜色优化: u3d/unity优化-相同模型的多个实例设置各自的颜色优化.md
  - unity创建新脚本自动添加版权声明，文件名，作者，创建时间等: u3d/unity创建新脚本自动添加版权声明，文件名，作者，创建时间等.md
  - unity发布android版本-so静态库打不进去: u3d/unity发布android版本-so静态库打不进去.md
  - unity和android交互bug: u3d/unity和android交互bug.md
  - unity性能优化总结: u3d/unity性能优化总结.md
  - unity接入声网sdk视频bug: u3d/unity接入声网sdk视频bug.md
  - unity矩阵变换从模型空间到屏幕空间的转换: u3d/unity矩阵变换从模型空间到屏幕空间的转换.md
  - unity禁止屏幕休眠: u3d/unity禁止屏幕休眠.md
  - unity脚本MonoBehaviour默认方法执行顺序测试: u3d/unity脚本MonoBehaviour默认方法执行顺序测试.md
  - unity设置屏幕分辨率: u3d/unity设置屏幕分辨率.md
  - unity读取StreamingAssets文本文件: u3d/unity读取StreamingAssets文本文件.md
  - untiy-ios透明ui-的透明区域渲染错误: u3d/untiy-ios透明ui-的透明区域渲染错误.md
  - xLua-第三方扩展的添加和编译: u3d/xLua-第三方扩展的添加和编译.md
  - xlua性能测试: u3d/xlua性能测试.md
  - 世界部队DrawCall分析和优化: u3d/世界部队DrawCall分析和优化.md
  - 使用TexturePacker命令行的一个坑: u3d/使用TexturePacker命令行的一个坑.md
  - 修改Prefab实例将Transform变为RectTransform: u3d/修改Prefab实例将Transform变为RectTransform.md
  - 苹果内购: u3d/苹果内购.md
- Unity 编辑器扩展:
  - 栏目首页: unity-editor/index.md
  - MeshRenderer在Inspector设置SorttingLayerName和SorttingOrder: unity-editor/MeshRenderer在Inspector设置SorttingLayerName和SorttingOrder.md
  - SerializedObject获取所有属性: unity-editor/SerializedObject获取所有属性.md
  - Unity编辑器扩展菜单项: unity-editor/Unity编辑器扩展菜单项.md
  - unity编辑器-自定义Inspector面板: unity-editor/unity编辑器-自定义Inspector面板.md
- Unity 工具:
  - 栏目首页: unityTool/index.md
  - ByteHelper字节数组辅助工具: unityTool/ByteHelper字节数组辅助工具.md
  - JsonHelper工具: unityTool/JsonHelper工具.md
  - Md5计算工具: unityTool/Md5计算工具.md
  - ProfilerHelper辅助工具: unityTool/ProfilerHelper辅助工具.md
  - StringHelper编码辅助工具: unityTool/StringHelper编码辅助工具.md
  - URLHelper-URL编码解码工具: unityTool/URLHelper-URL编码解码工具.md
  - Unity-Assert断言工具: unityTool/Unity-Assert断言工具.md
  - ZipHelper压缩工具: unityTool/ZipHelper压缩工具.md
  - 生成分布式唯一ID: unityTool/生成分布式唯一ID.md
  - 遍历打印对象的所有变量和属性: unityTool/遍历打印对象的所有变量和属性.md
plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_optional_attribute_quotes: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
  - git-authors

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - abbr
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.snippets

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
